
# ----------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Code generated by Microsoft (R) AutoRest Code Generator.Changes may cause incorrect behavior and will be lost if the code
# is regenerated.
# ----------------------------------------------------------------------------------

<#
.Synopsis

.Description

.Example
{{ Add code here }}
.Example
{{ Add code here }}

.Outputs
System.Object
.Notes
COMPLEX PARAMETER PROPERTIES

To create the parameters described below, construct a hash table containing the appropriate properties. For information on hash tables, run Get-Help about_Hash_Tables.

CUSTOMPROPERTY <IPlannedFailoverModelCustomProperties>: 
  InstanceType <String>: Gets or sets the instance type.

INPUTOBJECT <IProtectedItemModel>: 
  [CustomProperty <IProtectedItemModelCustomProperties>]: Protected item model custom properties.
    InstanceType <String>: Gets or sets the instance type.
  [PolicyName <String>]: Gets or sets the policy name.
  [ReplicationExtensionName <String>]: Gets or sets the replication extension name.
  [SystemDataCreatedAt <DateTime?>]: Gets or sets the timestamp of resource creation (UTC).
  [SystemDataCreatedBy <String>]: Gets or sets identity that created the resource.
  [SystemDataCreatedByType <String>]: Gets or sets the type of identity that created the resource: user, application,         managedIdentity.
  [SystemDataLastModifiedAt <DateTime?>]: Gets or sets the timestamp of resource last modification (UTC).
  [SystemDataLastModifiedBy <String>]: Gets or sets the identity that last modified the resource.
  [SystemDataLastModifiedByType <String>]: Gets or sets the type of identity that last modified the resource: user, application,         managedIdentity.
  [Tag <IProtectedItemModelTags>]: Gets or sets the resource tags.
    [(Any) <String>]: This indicates any property can be added to this object.
.Link
https://docs.microsoft.com/powershell/module/az.datareplication/start-azdatareplicationplannedfailoverjob
#>
function Start-AzDataReplicationPlannedFailoverJob {
[CmdletBinding(DefaultParameterSetName='ByProtectedItemId', PositionalBinding=$false)]
param(
    [Parameter(ParameterSetName='ByProtectedItemId', Mandatory)]
    [Parameter(ParameterSetName='ByProtectedItemIdExpanded', Mandatory)]
    [Microsoft.Azure.PowerShell.Cmdlets.DataReplication.Category('Path')]
    [System.String]
    ${ProtectedItemId},

    [Parameter()]
    [Microsoft.Azure.PowerShell.Cmdlets.DataReplication.Category('Path')]
    [Microsoft.Azure.PowerShell.Cmdlets.DataReplication.Runtime.DefaultInfo(Script='(Get-AzContext).Subscription.Id')]
    [System.String]
    ${SubscriptionId},

    [Parameter(ParameterSetName='ByProtectedItemId', Mandatory)]
    [Parameter(ParameterSetName='ByInputObject', Mandatory)]
    [Microsoft.Azure.PowerShell.Cmdlets.DataReplication.Category('Body')]
    [Microsoft.Azure.PowerShell.Cmdlets.DataReplication.Models.Api20210216Preview.IPlannedFailoverModelCustomProperties]
    # To construct, see NOTES section for CUSTOMPROPERTY properties and create a hash table.
    ${CustomProperty},

    [Parameter(ParameterSetName='ByProtectedItemIdExpanded', Mandatory)]
    [Parameter(ParameterSetName='ByInputObjectExpanded', Mandatory)]
    [Microsoft.Azure.PowerShell.Cmdlets.DataReplication.Category('Body')]
    [System.String]
    ${InstanceType},

    [Parameter(ParameterSetName='ByProtectedItemIdExpanded')]
    [Parameter(ParameterSetName='ByInputObjectExpanded')]
    [Microsoft.Azure.PowerShell.Cmdlets.DataReplication.Category('Body')]
    [System.String]
    ${RecoveryPointType},

    [Parameter(ParameterSetName='ByInputObjectExpanded', Mandatory)]
    [Parameter(ParameterSetName='ByInputObject', Mandatory)]
    [Microsoft.Azure.PowerShell.Cmdlets.DataReplication.Category('Body')]
    [Microsoft.Azure.PowerShell.Cmdlets.DataReplication.Models.Api20210216Preview.IProtectedItemModel]
    # To construct, see NOTES section for INPUTOBJECT properties and create a hash table.
    ${InputObject}
)

begin {
    try {
        $outBuffer = $null
        if ($PSBoundParameters.TryGetValue('OutBuffer', [ref]$outBuffer)) {
            $PSBoundParameters['OutBuffer'] = 1
        }
        $parameterSet = $PSCmdlet.ParameterSetName

        if ($null -eq [Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet]::PowerShellVersion) {
            [Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet]::PowerShellVersion = $Host.Version.ToString()
        }         
        $preTelemetryId = [Microsoft.WindowsAzure.Commands.Common.MetricHelper]::TelemetryId
        if ($preTelemetryId -eq '') {
            [Microsoft.WindowsAzure.Commands.Common.MetricHelper]::TelemetryId =(New-Guid).ToString()
            [Microsoft.Azure.PowerShell.Cmdlets.DataReplication.module]::Instance.Telemetry.Invoke('Create', $MyInvocation, $parameterSet, $PSCmdlet)
        } else {
            $internalCalledCmdlets = [Microsoft.WindowsAzure.Commands.Common.MetricHelper]::InternalCalledCmdlets
            if ($internalCalledCmdlets -eq '') {
                [Microsoft.WindowsAzure.Commands.Common.MetricHelper]::InternalCalledCmdlets = $MyInvocation.MyCommand.Name
            } else {
                [Microsoft.WindowsAzure.Commands.Common.MetricHelper]::InternalCalledCmdlets += ',' + $MyInvocation.MyCommand.Name
            }
            [Microsoft.WindowsAzure.Commands.Common.MetricHelper]::TelemetryId = 'internal'
        }

        $mapping = @{
            ByProtectedItemId = 'Az.DataReplication.custom\Start-AzDataReplicationPlannedFailoverJob';
            ByProtectedItemIdExpanded = 'Az.DataReplication.custom\Start-AzDataReplicationPlannedFailoverJob';
            ByInputObjectExpanded = 'Az.DataReplication.custom\Start-AzDataReplicationPlannedFailoverJob';
            ByInputObject = 'Az.DataReplication.custom\Start-AzDataReplicationPlannedFailoverJob';
        }
        if (('ByProtectedItemId', 'ByProtectedItemIdExpanded', 'ByInputObjectExpanded', 'ByInputObject') -contains $parameterSet -and -not $PSBoundParameters.ContainsKey('SubscriptionId')) {
            $PSBoundParameters['SubscriptionId'] = (Get-AzContext).Subscription.Id
        }
        $cmdInfo = Get-Command -Name $mapping[$parameterSet]
        [Microsoft.Azure.PowerShell.Cmdlets.DataReplication.Runtime.MessageAttributeHelper]::ProcessCustomAttributesAtRuntime($cmdInfo, $MyInvocation, $parameterSet, $PSCmdlet)
        $wrappedCmd = $ExecutionContext.InvokeCommand.GetCommand(($mapping[$parameterSet]), [System.Management.Automation.CommandTypes]::Cmdlet)
        $scriptCmd = {& $wrappedCmd @PSBoundParameters}
        $steppablePipeline = $scriptCmd.GetSteppablePipeline($MyInvocation.CommandOrigin)
        $steppablePipeline.Begin($PSCmdlet)
    } catch {
        [Microsoft.WindowsAzure.Commands.Common.MetricHelper]::ClearTelemetryContext()
        throw
    }
}

process {
    try {
        $steppablePipeline.Process($_)
    } catch {
        [Microsoft.WindowsAzure.Commands.Common.MetricHelper]::ClearTelemetryContext()
        throw
    }

    finally {
        $backupTelemetryId = [Microsoft.WindowsAzure.Commands.Common.MetricHelper]::TelemetryId
        $backupInternalCalledCmdlets = [Microsoft.WindowsAzure.Commands.Common.MetricHelper]::InternalCalledCmdlets
        [Microsoft.WindowsAzure.Commands.Common.MetricHelper]::ClearTelemetryContext()
    }

}
end {
    try {
        $steppablePipeline.End()

        [Microsoft.WindowsAzure.Commands.Common.MetricHelper]::TelemetryId = $backupTelemetryId
        [Microsoft.WindowsAzure.Commands.Common.MetricHelper]::InternalCalledCmdlets = $backupInternalCalledCmdlets
        if ($preTelemetryId -eq '') {
            [Microsoft.Azure.PowerShell.Cmdlets.DataReplication.module]::Instance.Telemetry.Invoke('Send', $MyInvocation, $parameterSet, $PSCmdlet)
            [Microsoft.WindowsAzure.Commands.Common.MetricHelper]::ClearTelemetryContext()
        }
        [Microsoft.WindowsAzure.Commands.Common.MetricHelper]::TelemetryId = $preTelemetryId

    } catch {
        [Microsoft.WindowsAzure.Commands.Common.MetricHelper]::ClearTelemetryContext()
        throw
    }
} 
}
